// prettier-ignore
export type PipeFunction = {
  <V, A>(v: V, f1: (v: V) => A): A;
  <V, A, B>(v: V, f1: (v: V) => A, f2: (v: A) => B): B;
  <V, A, B, C>(v: V, f1: (v: V) => A, f2: (v: A) => B, f3: (v: B) => C): C;
  <V, A, B, C, D>(v: V, f1: (v: V) => A, f2: (v: A) => B, f3: (v: B) => C, f4: (v: C) => D): D;
  <V, A, B, C, D, E>(v: V, f1: (v: V) => A, f2: (v: A) => B, f3: (v: B) => C, f4: (v: C) => D, f5: (v: D) => E): E;
  <V, A, B, C, D, E, F>(v: V, f1: (v: V) => A, f2: (v: A) => B, f3: (v: B) => C, f4: (v: C) => D, f5: (v: D) => E, f6: (v: E) => F): F;
  <V, A, B, C, D, E, F, G>(v: V, f1: (v: V) => A, f2: (v: A) => B, f3: (v: B) => C, f4: (v: C) => D, f5: (v: D) => E, f6: (v: E) => F, f7: (v: F) => G): G;
  <V, A, B, C, D, E, F, G, H>(v: V, f1: (v: V) => A, f2: (v: A) => B, f3: (v: B) => C, f4: (v: C) => D, f5: (v: D) => E, f6: (v: E) => F, f7: (v: F) => G, f8: (v: G) => H): H;
  <V, A, B, C, D, E, F, G, H, I>(v: V, f1: (v: V) => A, f2: (v: A) => B, f3: (v: B) => C, f4: (v: C) => D, f5: (v: D) => E, f6: (v: E) => F, f7: (v: F) => G, f8: (v: G) => H, f9: (v: H) => I): I;
  <V, A, B, C, D, E, F, G, H, I, J>(v: V, f1: (v: V) => A, f2: (v: A) => B, f3: (v: B) => C, f4: (v: C) => D, f5: (v: D) => E, f6: (v: E) => F, f7: (v: F) => G, f8: (v: G) => H, f9: (v: H) => I, f10: (v: I) => J): J;
  <V, A, B, C, D, E, F, G, H, I, J, K>(v: V, f1: (v: V) => A, f2: (v: A) => B, f3: (v: B) => C, f4: (v: C) => D, f5: (v: D) => E, f6: (v: E) => F, f7: (v: F) => G, f8: (v: G) => H, f9: (v: H) => I, f10: (v: I) => J, f11: (v: J) => K): K;
  <V, A, B, C, D, E, F, G, H, I, J, K, L>(v: V, f1: (v: V) => A, f2: (v: A) => B, f3: (v: B) => C, f4: (v: C) => D, f5: (v: D) => E, f6: (v: E) => F, f7: (v: F) => G, f8: (v: G) => H, f9: (v: H) => I, f10: (v: I) => J, f11: (v: J) => K, f12: (v: K) => L): L;
  <V, A, B, C, D, E, F, G, H, I, J, K, L, M>(v: V, f1: (v: V) => A, f2: (v: A) => B, f3: (v: B) => C, f4: (v: C) => D, f5: (v: D) => E, f6: (v: E) => F, f7: (v: F) => G, f8: (v: G) => H, f9: (v: H) => I, f10: (v: I) => J, f11: (v: J) => K, f12: (v: K) => L, f13: (v: L) => M): M;
  <V, A, B, C, D, E, F, G, H, I, J, K, L, M, N>(v: V, f1: (v: V) => A, f2: (v: A) => B, f3: (v: B) => C, f4: (v: C) => D, f5: (v: D) => E, f6: (v: E) => F, f7: (v: F) => G, f8: (v: G) => H, f9: (v: H) => I, f10: (v: I) => J, f11: (v: J) => K, f12: (v: K) => L, f13: (v: L) => M, f14: (v: M) => N): N;
  <V, A, B, C, D, E, F, G, H, I, J, K, L, M, N, O>(v: V, f1: (v: V) => A, f2: (v: A) => B, f3: (v: B) => C, f4: (v: C) => D, f5: (v: D) => E, f6: (v: E) => F, f7: (v: F) => G, f8: (v: G) => H, f9: (v: H) => I, f10: (v: I) => J, f11: (v: J) => K, f12: (v: K) => L, f13: (v: L) => M, f14: (v: M) => N, f15: (v: N) => O): O;
  <V, A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P>(v: V, f1: (v: V) => A, f2: (v: A) => B, f3: (v: B) => C, f4: (v: C) => D, f5: (v: D) => E, f6: (v: E) => F, f7: (v: F) => G, f8: (v: G) => H, f9: (v: H) => I, f10: (v: I) => J, f11: (v: J) => K, f12: (v: K) => L, f13: (v: L) => M, f14: (v: M) => N, f15: (v: N) => O, f16: (v: O) => P): P;
  <V, A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q>(v: V, f1: (v: V) => A, f2: (v: A) => B, f3: (v: B) => C, f4: (v: C) => D, f5: (v: D) => E, f6: (v: E) => F, f7: (v: F) => G, f8: (v: G) => H, f9: (v: H) => I, f10: (v: I) => J, f11: (v: J) => K, f12: (v: K) => L, f13: (v: L) => M, f14: (v: M) => N, f15: (v: N) => O, f16: (v: O) => P, f17: (v: P) => Q): Q;
  <V, A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R>(v: V, f1: (v: V) => A, f2: (v: A) => B, f3: (v: B) => C, f4: (v: C) => D, f5: (v: D) => E, f6: (v: E) => F, f7: (v: F) => G, f8: (v: G) => H, f9: (v: H) => I, f10: (v: I) => J, f11: (v: J) => K, f12: (v: K) => L, f13: (v: L) => M, f14: (v: M) => N, f15: (v: N) => O, f16: (v: O) => P, f17: (v: P) => Q, f18: (v: Q) => R): R;
  <V, A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S>(v: V, f1: (v: V) => A, f2: (v: A) => B, f3: (v: B) => C, f4: (v: C) => D, f5: (v: D) => E, f6: (v: E) => F, f7: (v: F) => G, f8: (v: G) => H, f9: (v: H) => I, f10: (v: I) => J, f11: (v: J) => K, f12: (v: K) => L, f13: (v: L) => M, f14: (v: M) => N, f15: (v: N) => O, f16: (v: O) => P, f17: (v: P) => Q, f18: (v: Q) => R, f19: (v: R) => S): S;
  <V, A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T>(v: V, f1: (v: V) => A, f2: (v: A) => B, f3: (v: B) => C, f4: (v: C) => D, f5: (v: D) => E, f6: (v: E) => F, f7: (v: F) => G, f8: (v: G) => H, f9: (v: H) => I, f10: (v: I) => J, f11: (v: J) => K, f12: (v: K) => L, f13: (v: L) => M, f14: (v: M) => N, f15: (v: N) => O, f16: (v: O) => P, f17: (v: P) => Q, f18: (v: Q) => R, f19: (v: R) => S, f20: (v: S) => T): T;
};

type $P<V> = V | Promise<V>

// prettier-ignore
export type AsyncPipeFunction = {
  <V, A>(v: V, f1: (v: V) => $P<A>): Promise<A>;
  <V, A, B>(v: V, f1: (v: V) => $P<A>, f2: (v: A) => $P<B>): Promise<B>;
  <V, A, B, C>(v: V, f1: (v: V) => $P<A>, f2: (v: A) => $P<B>, f3: (v: B) => $P<C>): Promise<C>;
  <V, A, B, C, D>(v: V, f1: (v: V) => $P<A>, f2: (v: A) => $P<B>, f3: (v: B) => $P<C>, f4: (v: C) => $P<D>): Promise<D>;
  <V, A, B, C, D, E>(v: V, f1: (v: V) => $P<A>, f2: (v: A) => $P<B>, f3: (v: B) => $P<C>, f4: (v: C) => $P<D>, f5: (v: D) => $P<E>): Promise<E>;
  <V, A, B, C, D, E, F>(v: V, f1: (v: V) => $P<A>, f2: (v: A) => $P<B>, f3: (v: B) => $P<C>, f4: (v: C) => $P<D>, f5: (v: D) => $P<E>, f6: (v: E) => $P<F>): Promise<F>;
  <V, A, B, C, D, E, F, G>(v: V, f1: (v: V) => $P<A>, f2: (v: A) => $P<B>, f3: (v: B) => $P<C>, f4: (v: C) => $P<D>, f5: (v: D) => $P<E>, f6: (v: E) => $P<F>, f7: (v: F) => $P<G>): Promise<G>;
  <V, A, B, C, D, E, F, G, H>(v: V, f1: (v: V) => $P<A>, f2: (v: A) => $P<B>, f3: (v: B) => $P<C>, f4: (v: C) => $P<D>, f5: (v: D) => $P<E>, f6: (v: E) => $P<F>, f7: (v: F) => $P<G>, f8: (v: G) => $P<H>): Promise<H>;
  <V, A, B, C, D, E, F, G, H, I>(v: V, f1: (v: V) => $P<A>, f2: (v: A) => $P<B>, f3: (v: B) => $P<C>, f4: (v: C) => $P<D>, f5: (v: D) => $P<E>, f6: (v: E) => $P<F>, f7: (v: F) => $P<G>, f8: (v: G) => $P<H>, f9: (v: H) => $P<I>): Promise<I>;
  <V, A, B, C, D, E, F, G, H, I, J>(v: V, f1: (v: V) => $P<A>, f2: (v: A) => $P<B>, f3: (v: B) => $P<C>, f4: (v: C) => $P<D>, f5: (v: D) => $P<E>, f6: (v: E) => $P<F>, f7: (v: F) => $P<G>, f8: (v: G) => $P<H>, f9: (v: H) => $P<I>, f10: (v: I) => $P<J>): Promise<J>;
  <V, A, B, C, D, E, F, G, H, I, J, K>(v: V, f1: (v: V) => $P<A>, f2: (v: A) => $P<B>, f3: (v: B) => $P<C>, f4: (v: C) => $P<D>, f5: (v: D) => $P<E>, f6: (v: E) => $P<F>, f7: (v: F) => $P<G>, f8: (v: G) => $P<H>, f9: (v: H) => $P<I>, f10: (v: I) => $P<J>, f11: (v: J) => $P<K>): Promise<K>;
  <V, A, B, C, D, E, F, G, H, I, J, K, L>(v: V, f1: (v: V) => $P<A>, f2: (v: A) => $P<B>, f3: (v: B) => $P<C>, f4: (v: C) => $P<D>, f5: (v: D) => $P<E>, f6: (v: E) => $P<F>, f7: (v: F) => $P<G>, f8: (v: G) => $P<H>, f9: (v: H) => $P<I>, f10: (v: I) => $P<J>, f11: (v: J) => $P<K>, f12: (v: K) => $P<L>): Promise<L>;
  <V, A, B, C, D, E, F, G, H, I, J, K, L, M>(v: V, f1: (v: V) => $P<A>, f2: (v: A) => $P<B>, f3: (v: B) => $P<C>, f4: (v: C) => $P<D>, f5: (v: D) => $P<E>, f6: (v: E) => $P<F>, f7: (v: F) => $P<G>, f8: (v: G) => $P<H>, f9: (v: H) => $P<I>, f10: (v: I) => $P<J>, f11: (v: J) => $P<K>, f12: (v: K) => $P<L>, f13: (v: L) => $P<M>): Promise<M>;
  <V, A, B, C, D, E, F, G, H, I, J, K, L, M, N>(v: V, f1: (v: V) => $P<A>, f2: (v: A) => $P<B>, f3: (v: B) => $P<C>, f4: (v: C) => $P<D>, f5: (v: D) => $P<E>, f6: (v: E) => $P<F>, f7: (v: F) => $P<G>, f8: (v: G) => $P<H>, f9: (v: H) => $P<I>, f10: (v: I) => $P<J>, f11: (v: J) => $P<K>, f12: (v: K) => $P<L>, f13: (v: L) => $P<M>, f14: (v: M) => $P<N>): Promise<N>;
  <V, A, B, C, D, E, F, G, H, I, J, K, L, M, N, O>(v: V, f1: (v: V) => $P<A>, f2: (v: A) => $P<B>, f3: (v: B) => $P<C>, f4: (v: C) => $P<D>, f5: (v: D) => $P<E>, f6: (v: E) => $P<F>, f7: (v: F) => $P<G>, f8: (v: G) => $P<H>, f9: (v: H) => $P<I>, f10: (v: I) => $P<J>, f11: (v: J) => $P<K>, f12: (v: K) => $P<L>, f13: (v: L) => $P<M>, f14: (v: M) => $P<N>, f15: (v: N) => $P<O>): Promise<O>;
  <V, A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P>(v: V, f1: (v: V) => $P<A>, f2: (v: A) => $P<B>, f3: (v: B) => $P<C>, f4: (v: C) => $P<D>, f5: (v: D) => $P<E>, f6: (v: E) => $P<F>, f7: (v: F) => $P<G>, f8: (v: G) => $P<H>, f9: (v: H) => $P<I>, f10: (v: I) => $P<J>, f11: (v: J) => $P<K>, f12: (v: K) => $P<L>, f13: (v: L) => $P<M>, f14: (v: M) => $P<N>, f15: (v: N) => $P<O>, f16: (v: O) => $P<P>): Promise<P>;
  <V, A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q>(v: V, f1: (v: V) => $P<A>, f2: (v: A) => $P<B>, f3: (v: B) => $P<C>, f4: (v: C) => $P<D>, f5: (v: D) => $P<E>, f6: (v: E) => $P<F>, f7: (v: F) => $P<G>, f8: (v: G) => $P<H>, f9: (v: H) => $P<I>, f10: (v: I) => $P<J>, f11: (v: J) => $P<K>, f12: (v: K) => $P<L>, f13: (v: L) => $P<M>, f14: (v: M) => $P<N>, f15: (v: N) => $P<O>, f16: (v: O) => $P<P>, f17: (v: P) => $P<Q>): Promise<Q>;
  <V, A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R>(v: V, f1: (v: V) => $P<A>, f2: (v: A) => $P<B>, f3: (v: B) => $P<C>, f4: (v: C) => $P<D>, f5: (v: D) => $P<E>, f6: (v: E) => $P<F>, f7: (v: F) => $P<G>, f8: (v: G) => $P<H>, f9: (v: H) => $P<I>, f10: (v: I) => $P<J>, f11: (v: J) => $P<K>, f12: (v: K) => $P<L>, f13: (v: L) => $P<M>, f14: (v: M) => $P<N>, f15: (v: N) => $P<O>, f16: (v: O) => $P<P>, f17: (v: P) => $P<Q>, f18: (v: Q) => $P<R>): Promise<R>;
  <V, A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S>(v: V, f1: (v: V) => $P<A>, f2: (v: A) => $P<B>, f3: (v: B) => $P<C>, f4: (v: C) => $P<D>, f5: (v: D) => $P<E>, f6: (v: E) => $P<F>, f7: (v: F) => $P<G>, f8: (v: G) => $P<H>, f9: (v: H) => $P<I>, f10: (v: I) => $P<J>, f11: (v: J) => $P<K>, f12: (v: K) => $P<L>, f13: (v: L) => $P<M>, f14: (v: M) => $P<N>, f15: (v: N) => $P<O>, f16: (v: O) => $P<P>, f17: (v: P) => $P<Q>, f18: (v: Q) => $P<R>, f19: (v: R) => $P<S>): Promise<S>;
  <V, A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T>(v: V, f1: (v: V) => $P<A>, f2: (v: A) => $P<B>, f3: (v: B) => $P<C>, f4: (v: C) => $P<D>, f5: (v: D) => $P<E>, f6: (v: E) => $P<F>, f7: (v: F) => $P<G>, f8: (v: G) => $P<H>, f9: (v: H) => $P<I>, f10: (v: I) => $P<J>, f11: (v: J) => $P<K>, f12: (v: K) => $P<L>, f13: (v: L) => $P<M>, f14: (v: M) => $P<N>, f15: (v: N) => $P<O>, f16: (v: O) => $P<P>, f17: (v: P) => $P<Q>, f18: (v: Q) => $P<R>, f19: (v: R) => $P<S>, f20: (v: S) => $P<T>): Promise<T>;
  <V, L>(v: V, ...fns: Function[]): Promise<L>;
};
