name: CI
on:
  push:
    branches:
      - main
      - next
      - beta
      - alpha
  pull_request:
    branches:
      - main
      - next
      - beta
      - alpha

jobs:
  commitlint:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 'lts/*'
      - name: Setup bun
        uses: oven-sh/setup-bun@v2
        with:
          version: latest
      - name: Print versions
        run: |
          git --version
          node --version
          npm --version
          bun --version
          bunx commitlint --version
      - name: Install commitlint
        run: |
          bun install conventional-changelog-conventionalcommits
          bun install commitlint@latest

      - name: Validate current commit (last commit) with commitlint
        if: github.event_name == 'push'
        run: bunx commitlint --last --verbose
      - name: Validate PR commits with commitlint
        if: github.event_name == 'pull_request'
        run: bunx commitlint --from ${{ github.event.pull_request.head.sha }}~${{ github.event.pull_request.commits }} --to ${{ github.event.pull_request.head.sha }} --verbose
